services:
  backend:
    build: 
      context: ./first_go  
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - ./first_go:/app
    environment:
      - PORT=8080
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - VUE_APP_API_URL=http://backend:8080
      - NODE_ENV=development
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    driver: bridge
